language: java
jdk:
- oraclejdk8
before_install:
  -openssl aes-256-cbc -K $encrypted_adc600dc461f_key -iv $encrypted_adc600dc461f_iv
    -in src\main\resources\application.properties.enc -out application.properties -d
